#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
version_script="${script_dir}/continuous_deb_version.sh"

tmp=$(mktemp -d)
trap 'rm -rf "${tmp}"' EXIT

cd "${tmp}"
git init -q

cat > package.xml <<'EOF'
<package format="3">
  <name>rqt_multiplot</name>
  <version>0.0.37</version>
</package>
EOF
package_xml_before=$(cat package.xml)

mkdir -p debian
cat > debian/changelog <<'EOF'
ros-jazzy-rqt-multiplot (0.0.37-0noble) noble; urgency=high

  * Auto-generated by bloom. Body still mentions (0.0.37-0noble).

 -- Test <test@example.com>  Tue, 29 Sep 2026 21:03:00 +0200

ros-jazzy-rqt-multiplot (0.0.12-0noble) noble; urgency=high

  * Older bloom entry.

 -- Test <test@example.com>  Wed, 13 Jan 2021 00:00:00 +0000
EOF

git add package.xml debian/changelog
GIT_AUTHOR_DATE='2026-09-29T21:03:00+0200' \
GIT_COMMITTER_DATE='2026-09-29T21:03:00+0200' \
GIT_AUTHOR_NAME='Test' \
GIT_AUTHOR_EMAIL='test@example.com' \
GIT_COMMITTER_NAME='Test' \
GIT_COMMITTER_EMAIL='test@example.com' \
  git commit -q -m 'test package'

eval "$("${version_script}" --changelog debian/changelog)"

[[ "${BASE}" == "0.0.37" ]]
[[ "${STAMP}" == "20260929190300" ]]
[[ "${CONTINUOUS_VERSION}" == "0.0.37~continuous.20260929190300.${SHA}" ]]
full_sha=$(git rev-parse HEAD)
[[ "${SHA}" == "${full_sha:0:7}" ]]

expected_first="ros-jazzy-rqt-multiplot (${CONTINUOUS_VERSION}-0noble) noble; urgency=high"
actual_first=$(head -n 1 debian/changelog)
[[ "${actual_first}" == "${expected_first}" ]]
grep -q 'Body still mentions (0.0.37-0noble).' debian/changelog
grep -q 'ros-jazzy-rqt-multiplot (0.0.12-0noble) noble; urgency=high' debian/changelog
[[ "$(cat package.xml)" == "${package_xml_before}" ]]

if command -v dpkg >/dev/null 2>&1; then
  dpkg --compare-versions "${CONTINUOUS_VERSION}-0noble" lt "0.0.37-0noble"
  dpkg --compare-versions "0.0.37~continuous.20260929180200.aaaaaaa-0noble" lt "${CONTINUOUS_VERSION}-0noble"
  dpkg --compare-versions "0.0.38~continuous.20260929190300.aaaaaaa-0noble" gt "0.0.37-1noble.20260101.000000"
  dpkg --compare-versions "0.0.38~continuous.20260929190300.aaaaaaa-0noble" lt "0.0.38-0noble"
fi

echo "continuous_deb_version_test: ok"
